#!/usr/bin/env bash
# Author: Nima Shafie
# =============================================================================
# lcov-source-build/bootstrap.sh
#
# Extracts vendored lcov 2.4 and Perl dependencies, then installs to the
# appropriate system-wide or per-user path.
#
# INSTALL MODES:
#   Admin (system-wide) : /opt/airgap-cpp-devkit/lcov/
#   User  (per-user)    : ~/.local/share/airgap-cpp-devkit/lcov/
#
#   Admin mode is attempted first. Falls back to user mode automatically
#   with a clear warning if admin rights are not available.
#
# USAGE:
#   bash lcov-source-build/bootstrap.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENDOR_DIR="${SCRIPT_DIR}/vendor"

# ---------------------------------------------------------------------------
# Source shared install-mode library
# ---------------------------------------------------------------------------
source "${REPO_ROOT}/scripts/install-mode.sh"
install_mode_init "lcov" "2.4"
install_log_capture_start

LCOV_INSTALL="${INSTALL_PREFIX}"
LCOV_BIN="${LCOV_INSTALL}/bin"
PERL_LIBS="${LCOV_INSTALL}/lib/perl5"

echo "=================================================================="
echo "  lcov-source-build"
echo "  Install prefix : ${LCOV_INSTALL}"
echo "  Date           : $(date)"
echo "=================================================================="

# ── 1. Verify SHA256 ─────────────────────────────────────────────────
bash "${SCRIPT_DIR}/scripts/verify.sh"

# ── 2. Extract lcov-2.4 ──────────────────────────────────────────────
LCOV_STAGE="${SCRIPT_DIR}/vendor/lcov-2.4"
if [[ -f "${LCOV_STAGE}/bin/lcov" ]]; then
    echo "[SKIP] vendor/lcov-2.4 already extracted"
else
    echo "[INFO] Extracting lcov-2.4.tar.gz..."
    tar -xf "${VENDOR_DIR}/lcov-2.4.tar.gz" -C "${VENDOR_DIR}"
    echo "[DONE] lcov-2.4 extracted"
fi

# ── 3. Extract perl-libs ─────────────────────────────────────────────
PERL_STAGE="${SCRIPT_DIR}/vendor/perl-libs"
if [[ -d "${PERL_STAGE}/lib/perl5" ]]; then
    echo "[SKIP] vendor/perl-libs already extracted"
else
    echo "[INFO] Extracting perl-libs.tar.gz..."
    tar -xf "${VENDOR_DIR}/perl-libs.tar.gz" -C "${VENDOR_DIR}"
    echo "[DONE] perl-libs extracted"
fi

# ── 4. Install to target prefix ──────────────────────────────────────
echo "[INFO] Installing lcov to ${LCOV_INSTALL}..."
mkdir -p "${LCOV_BIN}" "${PERL_LIBS}"

# Copy lcov binaries
cp -f "${LCOV_STAGE}/bin/lcov"    "${LCOV_BIN}/lcov"
cp -f "${LCOV_STAGE}/bin/genhtml" "${LCOV_BIN}/genhtml"
chmod +x "${LCOV_BIN}/lcov" "${LCOV_BIN}/genhtml"

# Copy lcov lib (lcovutil.pm and other lcov-internal modules)
cp -rf "${LCOV_STAGE}/lib/." "${LCOV_INSTALL}/lib/"

# Copy perl libs
cp -rf "${PERL_STAGE}/lib/perl5/." "${PERL_LIBS}/"

echo "[DONE] lcov installed to ${LCOV_INSTALL}"

# ── 5. Write env-setup hint ──────────────────────────────────────────
ENV_SETUP_HINT="${LCOV_INSTALL}/env-setup.sh"
cat > "${ENV_SETUP_HINT}" << ENVEOF
#!/usr/bin/env bash
# Auto-generated by lcov-source-build/bootstrap.sh
# Source this file to activate lcov in your shell:
#   source ${ENV_SETUP_HINT}
export PATH="${LCOV_BIN}:\${PATH}"
export PERL5LIB="${PERL_LIBS}\${PERL5LIB:+:\${PERL5LIB}}"
echo "[lcov] lcov bin  : ${LCOV_BIN}"
echo "[lcov] PERL5LIB  : ${PERL_LIBS}"
ENVEOF
chmod +x "${ENV_SETUP_HINT}"

# ── 6. Receipt + footer ──────────────────────────────────────────────
install_receipt_write "success" \
    "lcov:${LCOV_BIN}/lcov" \
    "genhtml:${LCOV_BIN}/genhtml"

install_mode_print_footer "success" \
    "lcov:${LCOV_BIN}/lcov" \
    "genhtml:${LCOV_BIN}/genhtml"

echo "  Activate lcov in your current shell:"
echo "    source ${ENV_SETUP_HINT}"
echo ""
echo "  Or use the repo-level env-setup:"
echo "    source ${SCRIPT_DIR}/scripts/env-setup.sh"
echo ""
