#!/usr/bin/env bash
# Author: Nima Shafie
# =============================================================================
# lcov-source-build/bootstrap.sh
#
# Extracts vendored lcov 2.4 and Perl dependencies, then installs to the
# appropriate system-wide or per-user path.
#
# USAGE:
#   bash lcov-source-build/bootstrap.sh [--prefix <path>]
#
# OPTIONS:
#   --prefix <path>   Install to a custom path instead of auto-detected
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENDOR_DIR="${SCRIPT_DIR}/vendor"
PREFIX_OVERRIDE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix) PREFIX_OVERRIDE="$2"; shift 2 ;;
        *) echo "ERROR: Unknown argument: $1" >&2; exit 1 ;;
    esac
done

source "${REPO_ROOT}/scripts/install-mode.sh"
[[ -n "${PREFIX_OVERRIDE}" ]] && export INSTALL_PREFIX_OVERRIDE="${PREFIX_OVERRIDE}"
install_mode_init "lcov" "2.4"
install_log_capture_start

LCOV_INSTALL="${INSTALL_PREFIX}"
LCOV_BIN="${LCOV_INSTALL}/bin"
PERL_LIBS="${LCOV_INSTALL}/lib/perl5"

echo "=================================================================="
echo "  lcov-source-build"
echo "  Install prefix : ${LCOV_INSTALL}"
echo "  Date           : $(date)"
echo "=================================================================="

# ── 1. Verify SHA256 ─────────────────────────────────────────────────
im_progress_start "Verifying vendor archives"
bash "${SCRIPT_DIR}/scripts/verify.sh"
im_progress_stop "Verification complete"

# ── 2. Extract lcov-2.4 ──────────────────────────────────────────────
LCOV_STAGE="${SCRIPT_DIR}/vendor/lcov-2.4"
if [[ -f "${LCOV_STAGE}/bin/lcov" ]]; then
    echo "[SKIP] vendor/lcov-2.4 already extracted"
else
    im_progress_start "Extracting lcov-2.4.tar.gz"
    tar -xf "${VENDOR_DIR}/lcov-2.4.tar.gz" -C "${VENDOR_DIR}"
    im_progress_stop "lcov-2.4 extracted"
fi

# ── 3. Extract perl-libs ─────────────────────────────────────────────
PERL_STAGE="${SCRIPT_DIR}/vendor/perl-libs"
if [[ -d "${PERL_STAGE}/lib/perl5" ]]; then
    echo "[SKIP] vendor/perl-libs already extracted"
else
    im_progress_start "Extracting perl-libs.tar.gz"
    tar -xf "${VENDOR_DIR}/perl-libs.tar.gz" -C "${VENDOR_DIR}"
    im_progress_stop "perl-libs extracted"
fi

# ── 4. Install to target prefix ──────────────────────────────────────
im_progress_start "Installing lcov to ${LCOV_INSTALL}"
mkdir -p "${LCOV_BIN}" "${PERL_LIBS}"
cp -rf "${LCOV_STAGE}/bin/." "${LCOV_BIN}/"
chmod +x "${LCOV_BIN}/"*
cp -rf "${LCOV_STAGE}/lib/." "${LCOV_INSTALL}/lib/"
cp -rf "${PERL_STAGE}/lib/perl5/." "${PERL_LIBS}/"
im_progress_stop "lcov installed"

# ── 5. Write env-setup hint ──────────────────────────────────────────
ENV_SETUP_HINT="${LCOV_INSTALL}/env-setup.sh"
cat > "${ENV_SETUP_HINT}" << ENVEOF
#!/usr/bin/env bash
# Auto-generated by lcov-source-build/bootstrap.sh
export PATH="${LCOV_BIN}:\${PATH}"
export PERL5LIB="${PERL_LIBS}\${PERL5LIB:+:\${PERL5LIB}}"
echo "[lcov] lcov bin  : ${LCOV_BIN}"
echo "[lcov] PERL5LIB  : ${PERL_LIBS}"
ENVEOF
chmod +x "${ENV_SETUP_HINT}"

# ── 6. Receipt + footer ──────────────────────────────────────────────
install_receipt_write "success" \
    "lcov:${LCOV_BIN}/lcov" \
    "genhtml:${LCOV_BIN}/genhtml"

install_env_register "${LCOV_BIN}"

install_mode_print_footer "success" \
    "lcov:${LCOV_BIN}/lcov" \
    "genhtml:${LCOV_BIN}/genhtml"

echo "  Activate lcov in your current shell:"
echo "    source ${ENV_SETUP_HINT}"
echo ""