#!/usr/bin/env bash
# Author: Nima Shafie
# =============================================================================
# install-hooks.sh — Wire the pre-commit hook into a host repository
#
# Called automatically by bootstrap.sh. Can also be run directly.
#
# What it does:
#   1. Verifies the submodule is present and initialised.
#   2. Installs hooks/pre-commit into the host repo's .git/hooks/.
#   3. Creates a per-repo hooks.conf inside the submodule for local overrides.
#      Config files (.clang-format, .clang-tidy) stay inside the submodule —
#      nothing is copied to the host repo root.
#   4. Verifies clang-format is available at bin/<platform>/ or on PATH.
#
# Usage (from host repo root):
#   bash .llvm-hooks/scripts/install-hooks.sh [--force] [--no-tidy]
#
# Options:
#   --force      Overwrite an existing pre-commit hook without prompting.
#   --no-tidy    Do not enable clang-tidy in the installed hooks.conf.
# =============================================================================

set -euo pipefail

FORCE=false
NO_TIDY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)   FORCE=true;   shift ;;
        --no-tidy) NO_TIDY=true; shift ;;
        -h|--help)
            echo "Usage: $0 [--force] [--no-tidy]"
            exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# 0.  Locate important paths
# ---------------------------------------------------------------------------
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${REPO_ROOT}" ]]; then
    echo "[install-hooks] NOTE: Not inside a git repository — hook installation skipped."
    echo "                Run this script again from inside a git repository to install"
    echo "                the pre-commit hook."
    exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMODULE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
HOOKS_SRC="${SUBMODULE_ROOT}/hooks"
CONFIG_SRC="${SUBMODULE_ROOT}/config"
GIT_HOOKS_DIR="${REPO_ROOT}/.git/hooks"

echo "[install-hooks] Host repository : ${REPO_ROOT}"
echo "[install-hooks] Submodule root  : ${SUBMODULE_ROOT}"

# ---------------------------------------------------------------------------
# 1.  Confirm the submodule looks sane
# ---------------------------------------------------------------------------
if [[ ! -f "${HOOKS_SRC}/pre-commit" ]]; then
    echo "[install-hooks] ERROR: pre-commit hook source not found at:" >&2
    echo "                ${HOOKS_SRC}/pre-commit"                     >&2
    echo "                Have you initialised the submodule?"         >&2
    echo "                  git submodule update --init --recursive"   >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 2.  Install the pre-commit hook
# ---------------------------------------------------------------------------
DEST_HOOK="${GIT_HOOKS_DIR}/pre-commit"
mkdir -p "${GIT_HOOKS_DIR}"

if [[ -f "${DEST_HOOK}" && "${FORCE}" == "false" ]]; then
    # Don't clobber if it's already our hook
    if grep -q "clang-llvm-style-formatter" "${DEST_HOOK}" 2>/dev/null; then
        echo "[install-hooks] pre-commit hook already installed — skipping."
        echo "                Use --force to reinstall."
    else
        echo "[install-hooks] WARNING: A pre-commit hook already exists at:"  >&2
        echo "                ${DEST_HOOK}"                                    >&2
        echo "                Use --force to overwrite, or merge manually."    >&2
        exit 1
    fi
else
    # On Unix: symlink so the submodule update propagates automatically.
    # On Windows (Git Bash): symlinks may not work without Developer Mode,
    # so fall back to a thin wrapper script that delegates to the submodule.
    if [[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* || "$(uname -s)" == CYGWIN* ]]; then
        # Windows — write a wrapper that delegates to the real hook.
        # Use the absolute path to the submodule captured at install time so
        # the wrapper is not dependent on a fixed submodule directory name.
        cat > "${DEST_HOOK}" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by clang-llvm-style-formatter/scripts/install-hooks.sh
# Do not edit — re-run install-hooks.sh --force to update.
exec "${HOOKS_SRC}/pre-commit" "\$@"
WRAPPER
        echo "[install-hooks] Installed wrapper pre-commit hook (Windows mode)."
    else
        # Unix — symlink
        ln -sf "${HOOKS_SRC}/pre-commit" "${DEST_HOOK}"
        echo "[install-hooks] Symlinked pre-commit hook."
    fi
    chmod +x "${DEST_HOOK}"
fi

# ---------------------------------------------------------------------------
# 3.  Config files stay inside the submodule — do NOT copy to repo root.
#
#     clang-format finds .clang-format by walking UP the directory tree from
#     the file being formatted. This means it will find the config at:
#       <submodule>/config/.clang-format
#     only if the pre-commit hook passes --style=file:<path> explicitly,
#     OR if a .clang-format exists in an ancestor of the files being checked.
#
#     For multi-project repos (where the submodule is one of several projects),
#     we do NOT pollute the repo root with config files. The pre-commit hook
#     passes --style=file: pointing at the submodule config directly.
#
#     If the host repo wants its own .clang-format, the developer can create
#     one manually. The submodule config is the default fallback.
# ---------------------------------------------------------------------------
echo "[install-hooks] Config files remain in submodule: ${CONFIG_SRC}"
echo "                The pre-commit hook references them directly."

# ---------------------------------------------------------------------------
# 4.  Install a per-repo hooks.conf if one doesn't already exist
# ---------------------------------------------------------------------------
# Per-repo hooks.conf lives inside the submodule, not the host repo root.
# This avoids polluting the host repo with submodule-specific config files.
REPO_CONF_DIR="${SUBMODULE_ROOT}/.llvm-hooks-local"
REPO_CONF="${REPO_CONF_DIR}/hooks.conf"
if [[ ! -f "${REPO_CONF}" ]]; then
    mkdir -p "${REPO_CONF_DIR}"
    cp "${CONFIG_SRC}/hooks.conf" "${REPO_CONF}"
    if [[ "${NO_TIDY}" == "true" ]]; then
        sed -i 's/^ENABLE_TIDY=.*/ENABLE_TIDY="false"/' "${REPO_CONF}"
    fi
    echo "[install-hooks] Created per-repo config at ${REPO_CONF}"
    echo "                Edit this file to customise behaviour for this repo."
else
    echo "[install-hooks] Per-repo config already exists — skipping."
fi

# ---------------------------------------------------------------------------
# 5.  Verify clang-format is available
# ---------------------------------------------------------------------------
echo ""
# Check all known locations in priority order:
# 1. pip venv (fastest install)
# 2. clang-llvm-source-build bin/ (optional LLVM build)
# 3. legacy bin/ inside formatter dir
# 4. system PATH
CF_BIN=""
for _candidate in     "${SUBMODULE_ROOT}/.venv/Scripts/clang-format.exe"     "${SUBMODULE_ROOT}/.venv/bin/clang-format"     "${SUBMODULE_ROOT}/../clang-llvm-source-build/bin/windows/clang-format.exe"     "${SUBMODULE_ROOT}/../clang-llvm-source-build/bin/linux/clang-format"     "${SUBMODULE_ROOT}/bin/windows/clang-format.exe"     "${SUBMODULE_ROOT}/bin/linux/clang-format"; do
    [[ -x "${_candidate}" ]] && { CF_BIN="${_candidate}"; break; }
done
[[ -z "${CF_BIN}" ]] && command -v clang-format &>/dev/null     && CF_BIN="$(command -v clang-format)"

if [[ -n "${CF_BIN}" ]]; then
    CF_VER="$("${CF_BIN}" --version 2>/dev/null | head -1)"
    echo "[install-hooks] clang-format found: ${CF_VER}"
    echo "                Location: ${CF_BIN}"
else
    echo "[install-hooks] ⚠  clang-format not found."
    echo "                Build from vendored source:"
    echo "                  bash ${SUBMODULE_ROOT}/scripts/build-clang-format.sh"
fi

echo ""
echo "[install-hooks] Installation complete ✓"
echo ""
echo "  The pre-commit hook will run automatically on every 'git commit'."
echo "  To manually test:  bash ${DEST_HOOK}"
echo "  To bypass (emergency only):  git commit --no-verify"
echo ""