#!/usr/bin/env bash
# =============================================================================
# install-hooks.sh — Wire the pre-commit hook into a host repository
#
# Run this script once from the ROOT of any repository that has
# clang-llvm-style-formatter checked out as a submodule at .llvm-hooks/.
#
# What it does:
#   1. Verifies the submodule is present and initialised.
#   2. Copies (or symlinks on Linux/macOS) the pre-commit hook into
#      the host repo's .git/hooks/.
#   3. Symlinks (or copies) the .clang-format and .clang-tidy config
#      files to the host repo root if they are not already present.
#   4. Checks that clang-format is reachable; offers to run setup-user-path.sh
#      if it is not.
#
# Usage (from host repo root):
#   bash .llvm-hooks/scripts/install-hooks.sh [--force] [--no-tidy]
#
# Options:
#   --force      Overwrite an existing pre-commit hook without prompting.
#   --no-tidy    Do not enable clang-tidy in the installed hooks.conf.
# =============================================================================

set -euo pipefail

FORCE=false
NO_TIDY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)   FORCE=true;   shift ;;
        --no-tidy) NO_TIDY=true; shift ;;
        -h|--help)
            echo "Usage: $0 [--force] [--no-tidy]"
            exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ---------------------------------------------------------------------------
# 0.  Locate important paths
# ---------------------------------------------------------------------------
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    echo "[install-hooks] ERROR: Not inside a git repository." >&2
    exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMODULE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
HOOKS_SRC="${SUBMODULE_ROOT}/hooks"
CONFIG_SRC="${SUBMODULE_ROOT}/config"
GIT_HOOKS_DIR="${REPO_ROOT}/.git/hooks"

echo "[install-hooks] Host repository : ${REPO_ROOT}"
echo "[install-hooks] Submodule root  : ${SUBMODULE_ROOT}"

# ---------------------------------------------------------------------------
# 1.  Confirm the submodule looks sane
# ---------------------------------------------------------------------------
if [[ ! -f "${HOOKS_SRC}/pre-commit" ]]; then
    echo "[install-hooks] ERROR: pre-commit hook source not found at:" >&2
    echo "                ${HOOKS_SRC}/pre-commit"                     >&2
    echo "                Have you initialised the submodule?"         >&2
    echo "                  git submodule update --init --recursive"   >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 2.  Install the pre-commit hook
# ---------------------------------------------------------------------------
DEST_HOOK="${GIT_HOOKS_DIR}/pre-commit"
mkdir -p "${GIT_HOOKS_DIR}"

if [[ -f "${DEST_HOOK}" && "${FORCE}" == "false" ]]; then
    # Don't clobber if it's already our hook
    if grep -q "clang-llvm-style-formatter" "${DEST_HOOK}" 2>/dev/null; then
        echo "[install-hooks] pre-commit hook already installed — skipping."
        echo "                Use --force to reinstall."
    else
        echo "[install-hooks] WARNING: A pre-commit hook already exists at:"  >&2
        echo "                ${DEST_HOOK}"                                    >&2
        echo "                Use --force to overwrite, or merge manually."    >&2
        exit 1
    fi
else
    # On Unix: symlink so the submodule update propagates automatically.
    # On Windows (Git Bash): symlinks may not work without Developer Mode,
    # so fall back to a thin wrapper script that delegates to the submodule.
    if [[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* || "$(uname -s)" == CYGWIN* ]]; then
        # Windows — write a wrapper
        cat > "${DEST_HOOK}" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by clang-llvm-style-formatter/scripts/install-hooks.sh
# Do not edit — re-run install-hooks.sh to update.
exec "\$(git rev-parse --show-toplevel)/.llvm-hooks/hooks/pre-commit" "\$@"
WRAPPER
        echo "[install-hooks] Installed wrapper pre-commit hook (Windows mode)."
    else
        # Unix — symlink
        ln -sf "${HOOKS_SRC}/pre-commit" "${DEST_HOOK}"
        echo "[install-hooks] Symlinked pre-commit hook."
    fi
    chmod +x "${DEST_HOOK}"
fi

# ---------------------------------------------------------------------------
# 3.  Place config files at repo root (symlink on Unix, copy on Windows)
# ---------------------------------------------------------------------------
_install_config() {
    local src="$1"
    local dest="${REPO_ROOT}/$(basename "${src}")"
    local name
    name="$(basename "${src}")"

    if [[ -e "${dest}" && "${FORCE}" == "false" ]]; then
        echo "[install-hooks] ${name} already exists at repo root — skipping."
        echo "                Use --force to overwrite."
        return
    fi

    if [[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* || "$(uname -s)" == CYGWIN* ]]; then
        cp -f "${src}" "${dest}"
        echo "[install-hooks] Copied ${name} to repo root (Windows)."
    else
        ln -sf "${src}" "${dest}"
        echo "[install-hooks] Symlinked ${name} to repo root."
    fi
}

_install_config "${CONFIG_SRC}/.clang-format"
_install_config "${CONFIG_SRC}/.clang-tidy"

# ---------------------------------------------------------------------------
# 4.  Install a per-repo hooks.conf if one doesn't already exist
# ---------------------------------------------------------------------------
REPO_CONF_DIR="${REPO_ROOT}/.llvm-hooks-local"
REPO_CONF="${REPO_CONF_DIR}/hooks.conf"
if [[ ! -f "${REPO_CONF}" ]]; then
    mkdir -p "${REPO_CONF_DIR}"
    cp "${CONFIG_SRC}/hooks.conf" "${REPO_CONF}"
    if [[ "${NO_TIDY}" == "true" ]]; then
        sed -i 's/^ENABLE_TIDY=.*/ENABLE_TIDY="false"/' "${REPO_CONF}"
    fi
    echo "[install-hooks] Created per-repo config at ${REPO_CONF}"
    echo "                Edit this file to customise behaviour for this repo."
    echo "                Add .llvm-hooks-local/hooks.conf to .gitignore if"
    echo "                you do not want to commit per-developer overrides."
else
    echo "[install-hooks] Per-repo config already exists — skipping."
fi

# ---------------------------------------------------------------------------
# 5.  Verify clang-format is available
# ---------------------------------------------------------------------------
echo ""
if command -v clang-format &>/dev/null; then
    CF_VER="$(clang-format --version 2>/dev/null | head -1)"
    echo "[install-hooks] clang-format found: ${CF_VER}"
else
    echo "[install-hooks] ⚠  clang-format not found on PATH."
    echo "                Run the following to configure your PATH:"
    echo "                  bash ${SUBMODULE_ROOT}/scripts/setup-user-path.sh --auto"
fi

echo ""
echo "[install-hooks] Installation complete ✓"
echo ""
echo "  The pre-commit hook will run automatically on every 'git commit'."
echo "  To manually test:  bash ${DEST_HOOK}"
echo "  To bypass (emergency only):  git commit --no-verify"
echo ""
